#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct  3 11:28:21 2021

@author: sayedakhan
"""

import requests
import pandas as pd

##Connect to API for Makeup Information

##Get request

jsonResponse = requests.get('http://makeup-api.herokuapp.com/api/v1/products.json')


##Check for status
jsonResponse.status_code
jsonResponse.json()

print(jsonResponse)

#Get request for Maybelline brand products

jsonResponse2 = requests.get('http://makeup-api.herokuapp.com/api/v1/products.json?brand=maybelline')
dataframe=pd.DataFrame(jsonResponse2.json())